### ISSUE TITLE
你好，我想请问一个关于热力图分布效果的问题。

### ISSUE THREAD

**Issue by 179992096** [DingSoung/CCHeatMap#2]
![21_497686_dd5cedfca05e0ee](https://user-images.githubusercontent.com/11768708/57840564-74b49880-77fb-11e9-8313-dc6a45278d91.png)

您好，我想用热力图作出这个效果，但是我不知道怎么去设置那个蓝色的脚型外圈，还有红色的融合区域做不到这么漂亮。

如果使用您的库能通过加点的方式做到这样的效果么？

**Comment by 179992096** [comment]
两个圆点过于靠近时，其中一个圆点会消失，具体原因还不明，未能吃透库里面的代码原理。

**Comment by song-react** [comment]
@179992096 热力图的数据是大量的 经纬度坐标，和每个坐标上的权重值， 而不是通过属性配置的。

你需要采集足够的数据才能形成一张图。

**Comment by 179992096** [comment]
> @179992096 热力图的数据是大量的 经纬度坐标，和每个坐标上的权重值， 而不是通过属性配置的。
> 
> 你需要采集足够的数据才能形成一张图。
